SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 465
SMTP_USER = "resolve102024@gmail.com"
SMTP_PASSWORD = "sdbm yjwi hztg dmxx"
ADMIN_EMAIL = "resolve102024@gmail.com"
ADMIN_PASSWORD = "LymeAdmin2026"
ADMIN_NOTIFICATION_EMAIL = "q.lamboley78@gmail.com"


