ADMIN_PASSWORD = "SeeALL"
ADMIN_NOTIFICATION_EMAIL = "q.lamboley78@gmail.com"

SMTP_USER = "resolve102024@gmail.com"
SMTP_PASSWORD = "sdbm yjwi hztg dmxx"
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 465
